fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

rest_user:
    resource: "@RESTUserBundle/Controller/"
    type:     annotation
    prefix:   /

rest_blog_admin:
    resource: "@RESTBlogBundle/Controller/Admin/"
    type:     annotation
    prefix:   /admin

rest_blog_front:
    resource: "@RESTBlogBundle/Controller/Blog/"
    type:     annotation
    prefix:   /

